services:
  - type: web
    name: elites-property-frontend
    env: static
    buildCommand: |
      npm cache clean --force
      rm -rf node_modules package-lock.json
      npm install --legacy-peer-deps --force
      CI=false npm run build
    staticPublishPath: ./build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: REACT_APP_API_URL
        value: https://elites-property-backend.onrender.com/api
      - key: REACT_APP_PAYSTACK_PUBLIC_KEY
        value: pk_test_cdb1a6261d6f98525d31ff79b1e7273179ec7eb8